### ISSUE TITLE
Error not being handled corrrectly in updaters

### ISSUE THREAD

**Issue by EduardoSimon** [ArkerLabs/event-sourcing-nestjs#1]
When a field of one event is null or undefined in an updater, due to a developer error, the output from the console is misleading. The error should point right to the updater and the field that was null || undefined.

In the following case the updater had the event.modified to null. Causing an error.
![image](https://user-images.githubusercontent.com/19764148/79551483-00811580-809a-11ea-81ca-26803a7ecd37.png)

And the output from the console was:

![image](https://user-images.githubusercontent.com/19764148/79551658-3f16d000-809a-11ea-82cd-59222cfcb247.png)

**Comment by Nytyr** [comment]
Closing, this is an external library bug.
